### ISSUE TITLE
Allow to provide an optional default value 

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-initial-state#138]
For some cases it might be useful to be able to provide a default value if no initial state is provided. This would help to simplify the code a bit as you could avoid requiring to catch errors:

```
let myState
try {
  myState = loadState('app', 'key')
} catch (e) {
  myState = 1234
}
```

would become:

```
let myState = loadState('app', 'key', 1234)
```

Any concerns @nextcloud/javascript ? Otherwise I'd prepare a PR.

**Comment by skjnldsv** [comment]
none, looks great!

**Comment by ChristophWurst** [comment]
Yes, that makes the flow a lot easier and allows the use of `const` instead of `let` :+1:
